FROM python:3.7

# The enviroment variable ensures that the python output is set straight
# to the terminal with out buffering it first
ENV PYTHONUNBUFFERED 1
ENV TERM=xterm

# Create root directory for our project in the container
RUN mkdir /mantistable

# Copy the current directory contents into the container
COPY . /mantistable

# Set the working directory
WORKDIR /mantistable

# Install npm dependecies
RUN curl -sL https://deb.nodesource.com/setup_10.x | bash - && apt-get install -y nodejs
RUN npm install

# Install python requiremensts
RUN pip install -r requirements-prod.txt
